# This is a basic workflow to help you get started with Actions

name: GetStaticSecretWorkflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  fetch_secrets:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Fetch static secrets from Akeyless
        id: GetStaticSecretWorkflow
        with:
          access-id: p-3a6ty4atla1wam
          access-type: access_key
          access-key: Soe1vEFk9guJPPxGjk3RwG8ee+CaP4nPrd1uXtXxbzM=
          api-url: https://192.168.72.29/akeyless-api/v2/
          static-secrets: |
            - name: "/static/secret-001"
              output-name: "my_first_secret"
              key: "imp"
            - name: "/static/secret-002"
              output-name: "my_second_secret"
      - name: Use Akeyless secret
        run: |
            echo "Step Outputs"
            echo "my_first_secret: ${{ steps.fetch-secrets.outputs.my_first_secret }}" >> secrets.txt
            echo "my_second_secret: ${{ steps.fetch-secrets.outputs.my_second_secret }}" >> secrets.txt
            
            echo "Environment Variables"
            echo "my_first_secret: ${{ env.my_first_secret }}" >> secrets.txt
            echo "my_second_secret: ${{ env.my_second_secret }}" >> secrets.txt