# This is a basic workflow to help you get started with Actions

name: fetch_secrets

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  fetch_secrets:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    steps:
    
      - name: Fetch static secrets from Akeyless
        uses: akeyless-community/akeyless-github-action@v1.0.1
        id: fetch_secrets
        with:
          access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
          access-type: jwt
          #gateway-url: https://ciphertrust.cpl-salesengineer.cloudns.ph/akeyless-api/
          api-url: https://ciphertrust.cpl-salesengineer.cloudns.ph/akeyless-api/v2/
          ca-certificate: ${{ secrets.AKEYLESS_CA_CERTIFICATE }}
          static-secrets: |
            - name: "/static/secret-002"
              output-name: "my_second_secret"

      - name: Use Akeyless secret
        run: |
            echo "Step Outputs"
           
            echo "my_second_secret: ${{ steps.fetch-secrets.outputs.my_second_secret }}" >> secrets.txt
            
            echo "Environment Variables"
           
            echo "my_second_secret: ${{ env.my_second_secret }}" >> secrets.txt